.TH EX1
.SH Name
EX1 - The Command Line
.SH Synopsis
Leanring the basics of file packaging and terminal navigation

.SH Description
.B Step(1)
Started by creating a folder using the mkdir command - miller_koby
.PP

.B Step(2)
Practiced using grep to find the phrase "android_dev" in the kernel.
.PP

.B Step(3)
Put the grep results into a text file named ex1.txt.
.PP

.B Step(4)
Took a screenshot of the grep command used. Also went to the directory containing the file that had our grep results and took a screenshot of the contents.
.PP

.B Step(5)
Moved our new ex1.txt file into the folder miller_koby that was created in Step 1.
.PP

.B Step(6)
Created ex1.tar from the miller_koby folder.
.PP

.B Step(7)
Compressed the ex1.tar file with gzup to make ex1.tar.gz.

.SH AUTHOR
Koby Miller
